---
- name: remove emacs
  hosts: local_vboxes
  remote_user: ansible

  tasks:
  - ansible.builtin.yum:
      name: emacs
      state: absent
      autoremove: true
    become: true
    when: ansible_os_family == "RedHat"
  - ansible.builtin.apt:
      name: emacs
      state: absent
      autoremove: true
    become: true
    when: ansible_os_family == "Debian"
    