---
- name: Install emacs
  hosts: local_vboxes
  remote_user: ansible

  tasks:
  - ansible.builtin.yum:
      name: emacs
      state: present
      update_cache: true
    become: true
    when: ansible_os_family == "RedHat"
  - ansible.builtin.apt:
      name: emacs
      state: present
      update_cache: true
    become: true
    when: ansible_os_family == "Debian"
    